variable "ami_id" {}
variable "ubuntu_ami_id" {}
variable "inst_type" {}
variable "key_name" {}
variable "sg_ids" {}
variable "subnet_id" {}
variable "vpc_id" {}
variable "aws_region" {}
variable "ins2sg_name" {}
variable "ins1sg_name" {}
variable "environment" {}
variable "solution" {}
